language: java
# whitelist
branches:
  only:
    - master

jdk:
  - oraclejdk7

# Use this to prepare the system to install prerequisites or dependencies
#  - sudo apt-get update
before_install: 
  - git clone https://code.google.com/p/asterixdb/
  - git clone https://code.google.com/p/hyracks/
  - cd hyracks/
  - mvn clean install -DskipTests

# Use this to install any prerequisites or dependencies necessary to run your build
install:
  - cd ../asterixdb/
  - mvn clean install -DskipTests
  - cd ../

# Use this to prepare your build for testing
# e.g. copy database configurations, environment variables, etc.
before_script:
  - mvn clean install -DskipTests=true

script:
  - mvn test

